{{ config(
    materialized='table',
    file_format='delta'
) }}

with trip_metrics as (
    select
        first_ingestion_date as service_date,
        route_id,
        route_short_name,
        drift_minutes,
        update_count,
        monotonicity_violation_count
    from {{ ref('departure_drift_metrics') }}
),

route_colors as (
    select route_short_name, route_group_name, hex_color, text_hex_color
    from (values
        ('YELLOW', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW ALT', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW EVENING', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW EVENING SATURDAY', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW LATE NIGHT', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW LATE NIGHT SATURDAY', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW LATE NIGHT SUNDAY', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW SATURDAY', 'Yellow', 'fcee1f', '000000'),
        ('YELLOW SUNDAY', 'Yellow', 'fcee1f', '000000'),
        ('YELLOWHOPPER', 'Yellow', 'fcee1f', '000000'),
        ('RED', 'Red', 'e7131a', 'ffffff'),
        ('RED SATURDAY', 'Red', 'e7131a', 'ffffff'),
        ('LAVENDER', 'Lavender', 'a78bc0', '000000'),
        ('LAVENDER ALT', 'Lavender', 'a78bc0', '000000'),
        ('LAVENDER SATURDAY', 'Lavender', 'a78bc0', '000000'),
        ('LAVENDER SUNDAY', 'Lavender', 'a78bc0', '000000'),
        ('BLUE', 'Blue', '355caa', 'ffffff'),
        ('GREEN EXPRESS', 'Green Express', '008063', 'ffffff'),
        ('GREEN EXPRESS ALT', 'Green Express', '008063', 'ffffff'),
        ('GREEN', 'Green', '008063', 'ffffff'),
        ('GREEN ALT', 'Green', '008063', 'ffffff'),
        ('GREEN EVENING', 'Green', '008063', 'ffffff'),
        ('GREEN EVENING SATURDAY', 'Green', '008063', 'ffffff'),
        ('GREEN LATE NIGHT', 'Green', '008063', 'ffffff'),
        ('GREEN LATE NIGHT SATURDAY', 'Green', '008063', 'ffffff'),
        ('GREEN LATE NIGHT SUNDAY', 'Green', '008063', 'ffffff'),
        ('GREEN SATURDAY', 'Green', '008063', 'ffffff'),
        ('GREEN SUNDAY', 'Green', '008063', 'ffffff'),
        ('GREENHOPPER', 'Green', '008063', 'ffffff'),
        ('GREENHOPPER EVENING', 'Green', '008063', 'ffffff'),
        ('GREENHOPPER EVENING SATURDAY', 'Green', '008063', 'ffffff'),
        ('ORANGE', 'Orange', 'f99f2a', '000000'),
        ('ORANGE ALT', 'Orange', 'f99f2a', '000000'),
        ('ORANGEHOPPER', 'Orange', 'f99f2a', '000000'),
        ('GREY', 'Grey', '808285', 'ffffff'),
        ('GREY ALT', 'Grey', '808285', 'ffffff'),
        ('GREY EVENING', 'Grey', '808285', 'ffffff'),
        ('GREY EVENING SATURDAY', 'Grey', '808285', 'ffffff'),
        ('GREY SATURDAY', 'Grey', '808285', 'ffffff'),
        ('GREY SUNDAY', 'Grey', '808285', 'ffffff'),
        ('BRONZE', 'Bronze', '9e8966', 'ffffff'),
        ('BRONZE ALT', 'Bronze', '9e8966', 'ffffff'),
        ('BROWN', 'Brown', '825622', 'ffffff'),
        ('BROWN ALT', 'Brown', '825622', 'ffffff'),
        ('GOLD', 'Gold', 'c7994a', '000000'),
        ('GOLD ALT', 'Gold', 'c7994a', '000000'),
        ('GOLDHOPPER', 'Gold', 'c7994a', '000000'),
        ('RUBY EVENING', 'Ruby', 'eb008b', 'ffffff'),
        ('RUBY EVENING SATURDAY', 'Ruby', 'eb008b', 'ffffff'),
        ('RUBY SATURDAY', 'Ruby', 'eb008b', 'ffffff'),
        ('RUBY SUNDAY', 'Ruby', 'eb008b', 'ffffff'),
        ('TEAL', 'Teal', '006991', 'ffffff'),
        ('TEAL EVENING', 'Teal', '006991', 'ffffff'),
        ('TEAL EVENING SATURDAY', 'Teal', '006991', 'ffffff'),
        ('TEAL LATE NIGHT', 'Teal', '006991', 'ffffff'),
        ('TEAL LATE NIGHT SATURDAY', 'Teal', '006991', 'ffffff'),
        ('TEAL LATE NIGHT SUNDAY', 'Teal', '006991', 'ffffff'),
        ('TEAL SATURDAY', 'Teal', '006991', 'ffffff'),
        ('TEAL SUNDAY', 'Teal', '006991', 'ffffff'),
        ('SILVER LIMITED EVENING', 'Silver Limited', 'cccccc', '000000'),
        ('SILVER LIMITED EVENING SATURDAY', 'Silver Limited', 'cccccc', '000000'),
        ('SILVER LIMITED SATURDAY', 'Silver Limited', 'cccccc', '000000'),
        ('SILVER LIMITED SUNDAY', 'Silver Limited', 'cccccc', '000000'),
        ('SILVER', 'Silver', 'cccccc', '000000'),
        ('SILVER EVENING', 'Silver', 'cccccc', '000000'),
        ('SILVER EVENING SATURDAY', 'Silver', 'cccccc', '000000'),
        ('SILVER EVENING SUNDAY', 'Silver', 'cccccc', '000000'),
        ('SILVER LATE NIGHT', 'Silver', 'cccccc', '000000'),
        ('SILVER SATURDAY', 'Silver', 'cccccc', '000000'),
        ('SILVER SUNDAY', 'Silver', 'cccccc', '000000'),
        ('NAVY', 'Navy', '2b3088', 'ffffff'),
        ('PINK', 'Pink', 'ffbfff', '000000'),
        ('PINK ALT', 'Pink', 'ffbfff', '000000'),
        ('LIME EVENING', 'Lime', 'b2d235', '000000'),
        ('LIME EVENING SATURDAY', 'Lime', 'b2d235', '000000'),
        ('LIME SATURDAY', 'Lime', 'b2d235', '000000'),
        ('LIME SUNDAY', 'Lime', 'b2d235', '000000'),
        ('RAVEN', 'Raven', '000000', 'ffffff'),
        ('ILLINI', 'Illini', '5a1d5a', 'ffffff'),
        ('ILLINI EVENING', 'Illini', '5a1d5a', 'ffffff'),
        ('ILLINI EVENING SATURDAY', 'Illini', '5a1d5a', 'ffffff'),
        ('ILLINI EVENING SUNDAY', 'Illini', '5a1d5a', 'ffffff'),
        ('ILLINI LIMITED', 'Illini Limited', '5a1d5a', 'ffffff'),
        ('ILLINI LIMITED EVENING', 'Illini Limited', '5a1d5a', 'ffffff'),
        ('ILLINI LIMITED EVENING SATURDAY', 'Illini Limited', '5a1d5a', 'ffffff'),
        ('ILLINI LIMITED SATURDAY', 'Illini Limited', '5a1d5a', 'ffffff'),
        ('ILLINI LIMITED SUNDAY', 'Illini Limited', '5a1d5a', 'ffffff'),
        ('LINK', 'Link', '6fccdd', '000000')
    ) as t(route_short_name, route_group_name, hex_color, text_hex_color)
)

select
    tm.service_date,
    tm.route_id,
    tm.route_short_name,
    coalesce(rc.route_group_name, tm.route_short_name) as route_group_name,
    coalesce(rc.hex_color, '808285') as hex_color,
    coalesce(rc.text_hex_color, 'ffffff') as text_hex_color,
    count(*) as observed_trip_count,
    avg(tm.drift_minutes) as avg_drift_minutes,
    percentile_approx(tm.drift_minutes, 0.5) as p50_drift_minutes,
    percentile_approx(tm.drift_minutes, 0.9) as p90_drift_minutes,
    percentile_approx(tm.drift_minutes, 0.95) as p95_drift_minutes,
    avg(tm.update_count) as avg_update_count,
    avg(tm.monotonicity_violation_count) as avg_monotonicity_violation_count,
    avg(case when tm.drift_minutes >= 2 then 1.0 else 0.0 end) as pct_trips_drift_ge_2_min,
    avg(case when tm.drift_minutes >= 5 then 1.0 else 0.0 end) as pct_trips_drift_ge_5_min,
    avg(case when tm.drift_minutes >= 10 then 1.0 else 0.0 end) as pct_trips_drift_ge_10_min
from trip_metrics tm
left join route_colors rc on tm.route_short_name = rc.route_short_name
group by tm.service_date, tm.route_id, tm.route_short_name, rc.route_group_name, rc.hex_color, rc.text_hex_color
